# Generated by Django 3.0.8 on 2020-07-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='names',
            new_name='name',
        ),
    ]
